# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200
  wandb_project: RoPADet_esc50_npn_option2

checkpoint:
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: true
  # restore_file: /media/SSD/tungtk2/fairseq/outputs/2022-03-22/13-57-49/checkpoints/checkpoint_last.pt

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: label
  profiling: false
  auto_encoder: false

dataset:
  num_workers: 1
  batch_size: 48
  skip_invalid_size_inputs_valid_test: true
  # validate_after_updates: 50
  # validate_interval: 1000
  valid_subset: test
  fixed_validation_seed: 1

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: RoPADet
  # zero_infinity: true
  # class_weights: [2.0, 0.7]
  # class_weights: [6.6, 0.6, 1.5]
  class_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

optimization:
  max_update: 1668
  max_epoch: 50
  lr: [1e-4]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08
  weight_decay: 4e-3

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.0, 0.20, 0.80]
  final_lr_scale: 0.09


model:
  _name: RoPADet
  w2v_path: ???
  profile_extractor_path: ???
  no_pretrained_weights: false
  apply_mask: true
  mask_prob: 0.3
  mask_channel_prob: 0.25
  mask_channel_length: 32
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 1
  freeze_finetune_updates: 0
  final_dropout: 0.1
  clf_output_dim: 50
