# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200
  wandb_project: wave2graph_ICBHI

checkpoint:
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: icbhi
  maximize_best_checkpoint_metric: true
  # restore_file: /media/SSD/tungtk2/fairseq/outputs/2022-03-22/13-57-49/checkpoints/checkpoint_last.pt

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: label
  num_mels: 192
  specaug: false
  wave2graph: true

dataset:
  num_workers: 1
  batch_size: 64
  skip_invalid_size_inputs_valid_test: true
  # validate_after_updates: 50
  # validate_interval: 1000
  valid_subset: valid

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: cross_entropy
  # zero_infinity: true
  # positive_class_weight: -1
  # class_weights: [3.0, 1.5, 0.7, 0.4]
  class_weights: [1.0, 1.0, 1.0, 1.0]
  gamma: 0.0

optimization:
  # max_update: 8600
  max_update: 4000000
  sentence_avg: true
  update_freq: [1]
  max_epoch: 200
  lr: [1e-4]
  # clip_norm: 1.25

optimizer:
  _name: sgd
  momentum: 0.9
  lr: [1e-4]
  # adam_betas: (0.9,0.98)
  # adam_eps: 1e-08
  weight_decay: 4e-3

lr_scheduler:
  # _name: tri_stage
  # phase_ratio: [0.05, 0.75, 0.2]
  # final_lr_scale: 0.05
  _name: fixed

model:
  _name: GraphOnlyNet
  graph_network: GCN
